# Generated by Django 4.0.4 on 2022-05-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('temp', models.FloatField()),
                ('hum', models.IntegerField()),
                ('rain', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Weather data',
            },
        ),
        migrations.CreateModel(
            name='Indexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_hazard_index', models.FloatField(default=0.0)),
                ('weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collector.weather')),
            ],
            options={
                'verbose_name_plural': 'Fire index',
            },
        ),
    ]
