# Generated by Django 4.0.4 on 2022-05-15 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 21, 44, 22, 204527, tzinfo=utc)),
        ),
    ]
