# Generated by Django 4.1 on 2022-11-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_weather_fire_hazard_index_daily_delete_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='region_id',
            field=models.IntegerField(default=1),
        ),
    ]
